### ISSUE TITLE
Keyboard keys ?

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [dozingcat/Vector-Pinball#103] opened 2022-02-09 13:27 UTC
Hi,

I am trying to construct a DIY pinball with an Odroid C2 and a keyboard.
Do you know if there is a list of activ key press tht interact with Vector Pinball ?

**Comment by Jacques-Olivier-Farcy** [comment] 2022-02-09 14:03
Actually i have tested with a keyboard.
I only find the "ESC" "Z" "!" "SPACE" working.
But when i launch the game i don't know how to choose the table or start a game with a key press

**Comment by Jacques-Olivier-Farcy** [comment] 2022-02-10 10:03
Here is the prototype
![vector](https://user-images.githubusercontent.com/19731340/153384085-9c7f0d7a-4cb0-4a79-9669-92567955bebf.jpg)

**Comment by bdtc** [comment] 2022-02-13 09:57
Some Android flips phones do not have a touch screen.  Hopefully you can make this game work with number and/or cursor keys.

**Comment by Jacques-Olivier-Farcy** [comment] 2022-03-13 15:57
Hi @dozingcat , any news about this issue ?

**Comment by dozingcat** [comment] 2022-03-15 04:12
I'm hoping to do a release in the next few weeks that will improve this.

**Comment by Jacques-Olivier-Farcy** [comment] 2022-03-15 17:55
Great news!

**Comment by dozingcat** [comment] 2022-03-18 03:27
Merged a PR that should hopefully let you do everything with keyboard or controller inputs. @Jacques-Olivier-Farcy if you have a chance could you see if this works for you? I can send an APK if building is inconvenient.

**Comment by Jacques-Olivier-Farcy** [comment] 2022-03-18 07:15
Hi Dozingcat, thank you a lot!

Yes if you can make an apk for me it would be great (i don't have the skills do do that).
I will give you feedbacks.

**Comment by dozingcat** [comment] 2022-03-18 15:19
You can download the APK from https://github.com/dozingcat/Vector-Pinball/releases/tag/v1.9.7-prerelease. When you run it, you should be able to navigate the menus with up and down arrow keys, and select with enter or spacebar. There are added buttons for starting and resuming the game. One thing I'm not sure of is how to send a "back" button press, which is necessary to pause the game and quit the app.

**Comment by bdtc** [comment] 2022-03-18 19:51
Works great on this flip phone.  It'd be nice to allow number keys to activate the flippers.  1,4,7,* for left, 3,6,9,# for right.  Right now the D-pad left/right does the flippers, the D-pad center selects menu items, and the back key exits.  All good.  Many thanks!

**Comment by Jacques-Olivier-Farcy** [comment] 2022-03-18 20:37
What is working for me :

UP / DOWN : Navigate in the menus
ENTER / SPACE BAR : Select
ESC : Going Back (Menus), and going back to the home screen of android
LEFT / RIGHT : Launch ball, activate left and right flipper

Some bugs :
In the Settings, using scpace bar jump to the last choice
Using space bar while playing crash the game

**Comment by dozingcat** [comment] 2022-03-19 01:25
Thanks for the reports! Not sure what's going on with the spacebar crash; I can't reproduce it so if you can get a stack trace that would help a lot.

**Comment by Jacques-Olivier-Farcy** [comment] 2022-03-20 11:56
I really enjoy playing!
![20220320_103521 (Moyen)](https://user-images.githubusercontent.com/19731340/159161015-3208c82b-42a6-48ff-8ea2-1d746b822784.jpg)
![20220320_103533 (Moyen)](https://user-images.githubusercontent.com/19731340/159161016-c665510b-f06e-4c54-90f0-336f46bcfc54.jpg)
![20220320_104418 (Moyen)](https://user-images.githubusercontent.com/19731340/159161018-61da36a4-eeff-4cdf-8b9e-5f1a440466da.jpg)

Next step: a nice wood box

**Comment by Jacques-Olivier-Farcy** [comment] 2022-03-20 11:57
In the last picture, we can see i have a kind of glitch effect on this screen

**Comment by bdtc** [comment] 2022-03-20 13:46
When using the up/down keys in the settings menu, it is hard to tell which menu item is selected.  The highlighted item is not very highlighted.  This is a problem with other programs as well, so it may be a system-wide issue instead of related to this particular program.

(I put this here because it is only an issue when using the keys instead of touch screen.)

**Comment by bdtc** [comment] 2022-03-20 13:48
> In the last picture, we can see i have a kind of glitch effect on this screen

Do you see it with your own eyes, or only in the camera photograph?  If it's only in the photograph, it may be related to the camera's scan rate interacting with the display's scan rate.

**Comment by Jacques-Olivier-Farcy** [comment] 2022-03-20 14:34
No i also see it with my own eyes, same as it is on the picture

**Comment by dozingcat** [comment] 2022-03-20 16:17
@Jacques-Olivier-Farcy: That's awesome! Regarding the display glitch, is there any difference if you enable or disable OpenGL in the preferences?

@bdtc: Yes, the default "focused" style is very subtle. (At least on modern Android versions; it's nicely distinctive on my OG Droid with Android 2.3). I think it's possible to customize the focused style and will look into that.

**Comment by Jacques-Olivier-Farcy** [comment] 2022-03-21 07:37
Hi,

One more suggestion…
The "back" key is actually "ESC" key.
But sometimes i type too many times, so i quit Vector Pinball.
I would like to find a way to avoid this.

Maybe separate back and quit key ? (I don't know if it's possible).
Maybe you'll have an idea abour this?

**Comment by Jacques-Olivier-Farcy** [comment] 2022-03-25 17:04
a version with rigid cardboard
![20220325_171519](https://user-images.githubusercontent.com/19731340/160167702-cbb9559f-9f11-4371-ba10-152c7e0bfb9d.jpg)
![20220325_171526](https://user-images.githubusercontent.com/19731340/160167708-45d852ca-0275-43d7-8451-fc322871f4c3.jpg)

**Comment by Jacques-Olivier-Farcy** [comment] 2022-03-25 17:05
And is there a way to modify the line size in the options with keys instead of keyboard ?

**Comment by dozingcat** [comment] 2022-03-26 06:01
@Jacques-Olivier-Farcy That looks great! I could make the "P" key pause but not quit, would that help? Not sure about the line size, that might need a custom preferences UI.

**Comment by Jacques-Olivier-Farcy** [comment] 2022-03-26 15:32
Yes the "P" would be great

**Comment by dozingcat** [comment] 2022-03-28 06:29
@Jacques-Olivier-Farcy there's an updated APK at https://github.com/dozingcat/Vector-Pinball/releases/tag/v1.10.0-prerelease1. It uses "P" to pause and has your French translations.

**Comment by Jacques-Olivier-Farcy** [comment] 2022-03-28 07:16
Thank you a lot !

**Comment by bdtc** [comment] 2022-03-28 12:19
For use with flip phones, it'd be nice to have some number keys control the flippers.
1,4,7 for left flipper, 2,5,8 for both, and 3,6,9 for right.  Maybe add *, 0, # as well.
This would reduce wear on the commonly-used D-pad keys.
Other than that, it's a lot of fun and an amusing way to spend a spare minute or three.

**Comment by Jacques-Olivier-Farcy** [comment] 2022-03-28 13:14
I have installed  the last version, all is working perfectly! 💯

**Comment by Jacques-Olivier-Farcy** [comment] 2022-03-28 17:22
Well, just a little thing, when going into the help menu, i can't go back, could P could be also the "back" key in the menus ?

**Comment by dozingcat** [comment] 2022-03-28 23:15
@Jacques-Olivier-Farcy are you not able to go back from the preferences screen as well, or is it only the help screen?

**Comment by Jacques-Olivier-Farcy** [comment] 2022-03-29 07:42
I still can use the "ESC" key to go back from the preferecenes or the help screen.

As i don't want that people could be able to leave the game, id' rather have another key to go back from these two menus.

There is also another UI possibility, you could add a "back" "activ" text so we could use the arrow to go to this activ text in the help and preferences's screens so it could be possible to go back with the "ENTER" or "SPACE BAR" key when the "activ" text is highlighted.

**Comment by dozingcat** [comment] 2022-03-30 04:42
Makes sense, added support for "P" to exit the help and preferences screens. It's vaguely consistent in that P now always takes you to the main game with the menu visible.

**Comment by Jacques-Olivier-Farcy** [comment] 2022-04-02 12:55
Hi @dozingcat , can you send me a new apk please ?

**Comment by dozingcat** [comment] 2022-04-02 20:31
Added build at https://github.com/dozingcat/Vector-Pinball/releases/tag/v1.10.0-prerelease1, it's the one that ends in 20220402.

**Comment by Jacques-Olivier-Farcy** [comment] 2022-04-04 07:58
Thanks !!

And my son playing with the first wood version :
![wood-vector-pinball](https://user-images.githubusercontent.com/19731340/161499756-5a0df4c7-64bf-407f-a7be-da59110ae345.jpg)

**Comment by dozingcat** [comment] 2022-04-09 17:59
Looks great! Version 1.10.0 is released and should have full keyboard support.

**Closed by dozingcat** 2022-04-09 17:59 UTC
